### ISSUE TITLE
Release process?

### ISSUE THREAD

**Issue by AWegnerGitHub** [huge-success/sanic-openapi#152]
What is the release process of this project? 

I see that 0.6.0 was released on Aug 11, 2019. There have been several PRs merged since that date, but [PyPI](https://pypi.org/project/sanic-openapi/) is still on that 0.6.0 version. When do these new merged changes get released?

**Comment by ahopkins** [comment]
@chenjr0719 Let me know if you need anything on this.

**Comment by chenjr0719** [comment]
OK, I think I can release a new version in recent days after I finish the changelog.

And maybe we can think about the release plan/schedule for this project.
If follow the release plan of `sanic` might be too frequently because this project is not active like `sanic`.
So, maybe we can try:
1. At least two releases per year. Maybe in January and July and this can also make sure this project can support the new LTS version.
2. Release by request. For example, if there is a new feature and many users want to use this new feature then they can open an issue to request a new version.

@ahopkins What do you think?

**Comment by ahopkins** [comment]
Why not both? Plan for January and July with whatever is on master. And also, if there is something more urgent, an interim build.

**Comment by chenjr0719** [comment]
Hi @AWegnerGitHub, I have release the `0.6.1` on PyPI. Please check and enjoy it. :smiley:
