### ISSUE TITLE
[Bug] Inheritance does not work

### ISSUE THREAD

**Issue by TechPriest001** [huge-success/sanic-openapi#177]
**Describe the bug**
According to the [documentation](https://sanic-openapi.readthedocs.io/en/latest/sanic_openapi/fields.html), inheritance is supported.  However, using the example code provided in the documentation, the expected structure containing members from both the base class and the subclass does not occur.  Instead, only the members from the subclass are shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/18144859/83776321-a63e1300-a64d-11ea-8607-2e03f585598a.png)

**To Reproduce**
Use example code that is provided in the documentation:
```python
from sanic import Sanic
from sanic.response import json

from sanic_openapi import doc, swagger_blueprint

app = Sanic()
app.blueprint(swagger_blueprint)

class User:
    username = doc.String("The name of your user account.")
    password = doc.String("The password of your user account.")


class UserInfo(User):
    first_name = doc.String("The first name of user.")
    last_name = doc.String("The last name of user.")


@app.get("/test")
@doc.produces(UserInfo)
async def test(request):
    return json({})

app.run(host="0.0.0.0", debug=True)
```

**Expected behavior**
UserInfo on the UI page should contain "username" and "password" members in addition to "first_name" and "last_name".

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

Package versions:
```
sanic==20.3.0
sanic-openapi==0.6.0
```

**Additional context**
Add any other context about the problem here. This might be how to fix this bug or some hint to fix it.

**Comment by chenjr0719** [comment]
Hi @TechPriest001 , thanks for your report. The model inheritance is new feature and we haven't released the latest version include this feature to PyPI yet. 😅 

To use this new feature, please install our master branch instead of using PyPI:

```shell
pip install git+https://github.com/huge-success/sanic-openapi.git
```

We also have the plan(in #176 ) to release `0.6.2` version to PyPI in recent days. If you do not hurry maybe you can wait for this release.

I also change the default document version to stable to avoid this happen again. Sorry for misleading you. I will close this issue first and if you still have any issue, please fell free to reopen this issue, thanks.


Best,
Jacob
