### ISSUE TITLE
doc in blueprint still documents entire app

### ISSUE THREAD

**Issue by mpandzo** [huge-success/sanic-openapi#35]
Even though document calls are only done in a blueprint, say a blue print with url prefix /bp/, swagger goes ahead and documents everything including routes in the root.

Is there a way to register or restrict the documenting for only the blueprint prefix?

**Comment by chenjr0719** [comment]
@mpandzo Are you still there? I want to confirm that what you talk about is blueprint scoped swagger?
For example:

test.py:
```python
from sanic import Sanic
from sanic.response import text
from bp import bp

app = Sanic()
app.static('/license', './LICENSE')
app.blueprint(bp)


@app.get('/')
def version(request):
    return text('0.0.1')

if __name__ == '__main__':
    app.run()

```

bp.py:
```python
from sanic import Blueprint
from sanic.response import text
from sanic_openapi import swagger_blueprint

blueprint = Blueprint('bp')
bp = Blueprint.group(blueprint, swagger_blueprint, url_prefix='/bp/')


@blueprint.get('')
def bp_echo(request):
    return text('foo')

```
Do you only want to see `bp_echo` be document in swagger?

**Comment by gtors** [comment]
Faced with same problem:

```python
from sanic import Sanic
from sanic.response import text
from bp import bp_public, bp_internal

app = Sanic()
app.static('/license', './LICENSE')
app.blueprint(bp_public)  # Swagger should process only this blueprint
app.blueprint(bp_internal)  # Swagger should ignore this blueprint

@app.get('/')
def version(request):
    return text('0.0.1')

if __name__ == '__main__':
    app.run()
```

For now, it's impossible to hide `bp_internal` from Swagger.

**Comment by chenjr0719** [comment]
Yep, it is impossible currently because `sanic_openapi` uses the router of `sanic` to generate the `swagger.json`. This will document all the routes include every blueprint's routes at `swagger.json`.

Some possible solutions:
1. After merge #80, using `exclude` at every route you don't want to document at `swagger`.
2. Add a list in `app.config`, when `sanic_openapi` generate the `swagger.json`, read this list to decide which blueprint should be or should not be document at `swagger`. Related code:
https://github.com/huge-success/sanic-openapi/blob/3b3410da07766d93d615271768e42123211f95d0/sanic_openapi/swagger.py#L78-L84
