### ISSUE TITLE
A little question of decorator

### ISSUE THREAD

**Issue by sunhailin-Leo** [huge-success/sanic-openapi#61]
When @doc decorator is front of the @cross_origin (Sanic-Cors), @doc will not effect. :flushed:

If like this @doc will not effect.
![_20180327214147](https://user-images.githubusercontent.com/17564655/37971080-af19c742-3207-11e8-9384-e5110e62b822.png)

When i change like this it work.
![_20180327214249](https://user-images.githubusercontent.com/17564655/37971149-d05c1810-3207-11e8-984e-6ddc183b8186.png)

**Comment by hampsterx** [comment]
the problem is the code is building up a dict (route_specs) using function as the key, adding a decorator before these decorators changes the function (as it's wrapped) so when its building out the final structure it's only finding the pre wrapped ones.

 this and others we could fix post #58 hint hint @ahopkins :)
