### ISSUE TITLE
Project looks dead

### ISSUE THREAD

**Issue by notnami** [huge-success/sanic-openapi#68]
The latest release contains at least one show-stopping bug (#50), and contains other errors. Meanwhile, there are 12 pull requests which have been sitting unmerged (and likely not even reviewed) for months.

It seems that @Typhon66 can no longer maintain this project. Is it possible to add another maintainer to the project and at least merge all the working PRs? I cannot dedicate a significant amount of time to this, but I would be willing to at least merge the PRs.

If @Typhon66 and @channelcat are not active, and cannot add another maintainer, the repository should probably be forked.

**Comment by kivo360** [comment]
Holy crap that's a lot PR. Is there anyway to link people from outside of this project to help out? It seems pretty useful for the life of sanic.

**Comment by autogestion** [comment]
Any volunteer, which ready to maintain a fork? :)

**Comment by abatilo** [comment]
There's a pseudo fork, with attrs support:
https://github.com/vltr/sanic-attrs/

**Comment by DirkGuijt** [comment]
Sanic has turned into a community driven project now (https://sanicframework.org/) and the community has gained control over the releases, PRs and such. There are no clear plans on sanic-openapi yet, but it might become community driven as well. At least control of the project is in the same hands as the sanic project now. So better times ahead I think...

**Comment by ahopkins** [comment]
@DirkGuijt Thanks for posting this. As you said, we are working to build the community, and have this repo and the `sanic` repo under the same umbrella right now. Just today we put up a discussion board: https://community.sanicframework.org/.

To be entirely honest, most (if not all) of the attention has been on organizing `sanic`. Not that this repo has been forgotten, but we only have so many volunteers right now.

@abatilo, if you would like to take your fork and bring it back into the main, we would certainly welcome someone to stand up and help champion `sanic-openapi`.

**Comment by vltr** [comment]
@DirkGuijt sorry for haven't find time to jump in this issue before. Yes, indeed, `sanic-openapi` does need **A LOT** of care because it really seems abandoned for some time now. Even I made a fork of it called [sanic-attrs](https://github.com/vltr/sanic-attrs), which I later archived in favour of @abatilo 's [sanic-swagger](https://github.com/abatilo/sanic-swagger).

As @ahopkins stated, we have full attention on Sanic right now because it needs a lot of work, not only in code, but quality, documentation and the list can go on and on.

I'm also working hard on a component injection system for Sanic that will allow developers to provide some extra functionality to their endpoints and even extract and provide, if the user wants to, a OpenAPI / Swagger definition of their endpoints using Python type annotations (you can see [my comment describing part of the idea in here](https://github.com/vltr/sanic-attrs/pull/2#issuecomment-419482469)).

Of course I would like to see this on Sanic, but that will likely not happen in the near future nor I'll know if I would be able to provide a fully compatible plugin for Sanic or would have to override a lot of it's core functionalities (like I'm doing right now) to make this sort of thing to work properly.

**Comment by abatilo** [comment]
@ahopkins That would be awesome. What steps do I need to take to get that started?

**Comment by ahopkins** [comment]
@abatilo Welcome to the team. 😁

**Comment by abatilo** [comment]
@ahopkins Thank you! Happy to be here. Random question. Does anyone have the sanic-openapi PyPI credentials? Otherwise we might just want to rename this repo and stick with the sanic-swagger PyPI entry that I started?

**Comment by ahopkins** [comment]
We are working on it: https://github.com/pypa/warehouse/issues/4832

I am closing this issue for because @abatilo is going to help us bring it back from the dead. 👍 Feel free to carry on the conversation.

I think we should try and keep the `sanic-openapi` for now. It already has a significant usage, and seems less disruptive.

**Comment by vltr** [comment]
Agreed! Welcome, @abatilo ! :muscle:
