### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by mackeyja92** [huge-success/sanic-openapi#71]
This project looks in need of some assistance. There are several open PRs with some greatly needed fixes. Willing to assist as needed.

**Comment by ahopkins** [comment]
@mackeyja92 Awesome! @abatilo was also willing to work on this ... not sure where he is at. I think we need to start a conversation about how to bring this "back online".

**Comment by abatilo** [comment]
Last I remember, we were trying to figure out how to get the PyPI
credentials so that we can actually work on this and update it. Has that
changed at all?

**Comment by ahopkins** [comment]
Yes, we have pypi access

**Comment by ahopkins** [comment]
I'm thinking we need to add a new team and setup a discussion on the forum. What else?

**Comment by jstriebel** [comment]
Any news here? Tbh, the project seems to be quite dead right now.

**Comment by ahopkins** [comment]
Dead.... yup. No one has stepped in to maintain it. I'm starting to think it's time to put up a disclaimer on the README. 

Anyone out there in taking this in please send me a message on the community forums.

**Comment by hampsterx** [comment]
well you have pypi access, that is great! The code base itself is very small, I am willing to help maintain it, looks like I am not the only one offering also.

**Comment by DirkGuijt** [comment]
I agree, let's first merge some long awaited stuff and go from there. It's better than nothing.

**Comment by ahopkins** [comment]
OK. I will look over the PRs and merge what I can. But, I've never used this, nor do I have the time to maintain it going forward so I'm still happy to give access to someone that wants to do something with this.

**Comment by jstriebel** [comment]
Ok, I just had a look at different places of people that might have or already mentioned their interest in taking over this repository:
* @DirkGuijt (PR https://github.com/huge-success/sanic-openapi/pull/58)
* @chenjr0719 ([note in forum](https://community.sanicframework.org/t/status-of-sanic-openpai/156/5))
* @abatilo (this gh thread)
* @mackeyja92 (this gh thread)
* @FerdinaKusumah (recently updated [own repo](https://github.com/FerdinaKusumah/sanic_simple_swagger))

I'm just trying to gather the different threads here. If you want to maintain this repo, (I'd guess the more maintainers the better), please contact @ahopkins [on the forum](https://community.sanicframework.org/u/ahopkins).

PS: I'd be happy to contribute myself, but don't have enough time to actually maintain it.

**Comment by ahopkins** [comment]
@jstriebel You rock. Thanks for pulling this together. @hampsterx and @DirkGuijt have just been added as maintainers. @abatilo, if you are still interested, let me know.

Anyone else that may also want a hand, please contact me as mentioned. I am closing this now because I am *hopeful* that this project will be on a new course going forward.

**Comment by FerdinaKusumah** [comment]
sorry I was late in replying, I saw that this project was not maintained anymore so I decided to add the features I needed in my development and upload them again on Pypi, I would be happy if I could help develop this project, please make me a maintainer too @ahopkins in order to be able to add some additional features.
